version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./event-management-app/backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eventdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./event-management-app/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./event-management-app/frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 